### ISSUE TITLE
NilsHud Compatibility

### ISSUE THREAD

**Issue by Mi6kbuttface** [Rumi727/Jetpack-HMD#1]
Hello, 
It appears that when NilsHUD and JetpackHMD are installed together, the JetpackHMD UI ceases to pop up. 
I've also reported this issue in their GitHub as well.

Another thing I would like to ask for is the customization option for the color of the UI, as green is good and accurate, but I would like it to fit better with the hud I have so adding the ability to set the color would be a great feature, Thank You!

NilsHud: https://thunderstore.io/c/lethal-company/p/Nilaier/NilsHUD/
NilsHud Github: https://github.com/NilaierMusic/NilsHUD

**Comment by Rumi727** [comment]
I just installed and checked the NilsHUD mod, and it displayed normally.
Please make sure you are using version v1.0.5 or higher.
There is a bug in versions below v1.0.4 where multiplayer and certain modes are not displayed properly due to timing issues.

\+ I will add color change settings.

**Comment by Rumi727** [comment]
Oh, I didn't know, but I tested it on version v49.
In v50 it seems to conflict with the mod.
I'll check

**Comment by Rumi727** [comment]
It conflicts with the NilsHUD mod, but also appears to conflict with the [JetpackFallFix](https://github.com/Hamunii/JetpackFallFix) mod.
[JetpackFallFix](https://github.com/Hamunii/JetpackFallFix) mod does not work in v50 and also has bugs fixed in vanilla so you don't need to use it.
If you are using JetpackFallFix mod, please disable it.

**Comment by Rumi727** [comment]
I found out what the problem was

In v50, using JetpackFallFix mod or NilsHud mod together causes a crash.
The JetpackFallFix mod is already fixed in vanilla, so disabling it will solve it.
The NilsHud mode can be resolved by lowering the LethalConfig version to 1.4.0 until the NilsHud mode is updated, as described in https://github.com/NilaierMusic/NilsHUD/issues/4#issuecomment-2069714181.

Color change settings will probably be updated in 1-2 hours. :D
Thank you for using my mod

**Comment by Rumi727** [comment]
I just uploaded a version with color changing feature added!

**Comment by Mi6kbuttface** [comment]
Thank you so much, love yall!
